name: example

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  graph_layout:
    path: ../../graph_layout
  graph_display:
    path: ../
  http: ^0.13.5
  vector_math: ^2.1.2

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
