name: graph_layout
description: A package providing graph layout algorithms and related data structures.
version: 0.0.1
homepage: https://github.com/CicadaCinema/graphs/tree/master/graph_layout
repository: https://github.com/CicadaCinema/graphs

environment:
  sdk: '>=2.18.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
