name: graph_display
description: A package providing widgets for displaying graph structures in Flutter.
version: 0.0.1
homepage: https://github.com/CicadaCinema/graphs/tree/master/graph_display
repository: https://github.com/CicadaCinema/graphs

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  async: ^2.10.0
  flutter:
    sdk: flutter
  # TODO: Make this a hosted dependency eventually.
  graph_layout:
    path: ../graph_layout
  vector_math: ^2.1.2

dev_dependencies:
  flutter_lints: ^2.0.0
