# Reference: https://github.com/actions/starter-workflows/blob/main/pages/static.yml

name: Demo deployment

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Resolve dependencies
        run: flutter pub get
        working-directory: graph_layout/example
      - name: Build demo for the web
        run: flutter build web
        working-directory: graph_layout/example
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: graph_layout/example/build/web
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
