name: Calculate pub points for graph_display

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Activate pana
        run: dart pub global activate pana

      - name: Run pana
        # We lose 20 points because pana does not play well with GitHub Actions:
        # - 10 are lost to `Unable to detect Flutter version.`
        # - 10 are lost to issues with processing the example screenshot
        run: dart pub global run pana --no-warning --exit-code-threshold 20 graph_display
