name: Calculate pub points for graph_display

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Identify if Flutter is available
        run: which flutter | xargs dirname

      - name: Identify Flutter SDK path
        run: which flutter | xargs dirname | xargs dirname

      - name: Activate pana
        run: dart pub global activate pana

      - name: Run pana
        run: dart pub global run pana --no-warning --flutter-sdk `which flutter | xargs dirname | xargs dirname` --exit-code-threshold 0 graph_display

